[tox]
envlist = py310
skipsdist = True

[testenv]
allowlist_externals =
    /bin/bash
    cp

setenv =
    PYTHONPATH = {toxinidir}/src:{toxinidir}/tests
    LOG_APP_NAME = test_app
    LOG_GROUP_NAME = test_group_cloudwatch
    AWS_DEFAULT_REGION = us-east-1
    ; JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_311.jdk/Contents/Home
    ;JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
    
export JAVA_HOME=
passenv = PYTHONPATH,LOG_APP_NAME,LOG_GROUP_NAME

deps =
    -rtest_requirements.txt
    -rrequirements.txt
    
commands =
    pycodestyle --ignore E501,E302,E303,W503 src
    pycodestyle --ignore E501,E302,E303,W503,W391 tests
    pylint --recursive=y --disable=C0302,C0114,C0115,R0903,C0103,E1205,C0301,R0912,R0914,R0913,W1514,R0801,E0401,W0401,E0611,W0622,R0915,R1702,W0632,R0911,R0904 src
    # cp jars/iceberg-spark-runtime-3.5_2.12-1.5.2.jar .tox/py310/lib/python3.10/site-packages/pyspark/jars/
    pytest -v --cov-report term-missing --cov-fail-under=80 --cov=src tests
